services:
  - type: web
    name: cpa-meta-service
    env: node
    region: oregon
    plan: starter
    buildCommand: yarn install && pip install -U yt-dlp
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4001
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
